[package]
name = "polytype"
version = "1.0.0"
authors = ["Lucas Morales <lucas@lucasem.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucasem/polytype"
homepage = "https://github.com/lucasem/polytype"
documentation = "https://docs.rs/polytype"
description = "A Hindley-Milner polymorphic typing system."
keywords = ["typing", "language", "type", "inference", "unification"]
categories = ["science", "data structures", "algorithms"]

[dependencies]
itertools = "0.7.6"
